name: artourguide_new
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  cloud_firestore: ^4.15.9
  image_picker: ^1.0.7
  tflite_flutter: ^0.11.0
  image: ^4.1.7
  camera: ^0.10.5+9
  cupertino_icons: ^1.0.8
  vector_math: ^2.1.4
  sceneview_flutter:
    path: packages/sceneview_flutter
  path_provider: ^2.1.2
  permission_handler: ^12.0.0+1
  firebase_storage: ^11.6.10
  geolocator: ^11.0.0
  google_places_flutter: ^2.0.6
  yuv_converter: ^0.0.2
  http: ^1.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

dependency_overrides:
  permission_handler_android: ^13.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/models/
    - assets/labels/
    - assets/model/model.tflite
    - assets/model/labels.txt
    - assets/brush_strokes.png
    - assets/model/loc/1.tflite
    - assets/model/loc/labels.txt

  fonts:
    - family: Merriweather
      fonts:
        - asset: assets/fonts/Merriweather-Regular.ttf
        - asset: assets/fonts/Merriweather-Bold.ttf
          weight: 700
    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/PlayfairDisplay-Regular.ttf
        - asset: assets/fonts/PlayfairDisplay-Bold.ttf
          weight: 700
        - asset: assets/fonts/PlayfairDisplay-Italic.ttf
          style: italic