name: artourguide_new
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  cloud_firestore: ^4.15.9
  image_picker: ^1.0.7
  tflite_flutter: ^0.11.0
  image: ^4.1.7
  camera: ^0.10.5+9
  cupertino_icons: ^1.0.8
  vector_math: ^2.1.4
  sceneview_flutter:
    path: packages/sceneview_flutter
  path_provider: ^2.1.2
  permission_handler: ^12.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

dependency_overrides:
  permission_handler_android: ^13.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/model/model.tflite
    - assets/model/labels.txt

  fonts:
    - family: Merriweather
      fonts:
        - asset: assets/fonts/Merriweather-Regular.ttf
        - asset: assets/fonts/Merriweather-Bold.ttf
          weight: 700 