name: sceneview_flutter
description: A demonstration of how to integrate SceneView in flutter.
version: 0.0.1
homepage: https://github.com/SceneView

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: io.github.sceneview.sceneview_flutter
        pluginClass: SceneviewFlutterPlugin