name: tflite_flutter
description: TensorFlow Lite plugin for Flutter
version: 0.9.5

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.tfliteflutter.tflite_flutter_plugin
        pluginClass: TfliteFlutterPlugin 